services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: nexusai-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_strong_password123"
    ports:
      - "1433:1433"
    volumes:
      - nexusai-sql-data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "Your_strong_password123" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: nexusai-keycloak
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
    ports:
      - "8080:8080"
    volumes:
      - ./infra/keycloak:/opt/keycloak/data/import

  redis:
    image: redis:7-alpine
    container_name: nexusai-redis
    ports:
      - "6380:6379"
    volumes:
      - nexusai-redis-data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: nexusai-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  jaeger:
    image: jaegertracing/all-in-one:1.76.0
    container_name: nexusai-jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"

volumes:
  nexusai-sql-data:
  nexusai-redis-data:
